name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Test with pytest
      run: python3 test.py > stdout.txt 2> stderr.txt
        
